version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: development/docker/nginx.docker
        volumes:
            - ./:/var/www
        links:
            - app
        expose:
            - 8090
        environment:
            - VIRTUAL_HOST=lchiangmai-movies.seenelf.com
            - VIRTUAL_PORT=8090
    app:
        build:
            context: ./
            dockerfile: development/docker/php7.docker
        volumes:
            - ./:/var/www

    database:
        image: mysql:5.7
        environment:
            - "MYSQL_DATABASE=chiangmai_movies"
            - "MYSQL_ROOT_PASSWORD=password"
        volumes:
            # add database dump in the folder, docker will dump it into the db
            - ./development/sql-dump:/docker-entrypoint-initdb.d
            # keep database binary outside container
            - ./development/sql-binary:/var/lib/mysql

    phpmyadmin:
        image:  phpmyadmin/phpmyadmin
        links:
            - database:db

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          - 80:80
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
          - web